Repository kendryte/k510_docs, pull requests merged in 2022-05, with the labels that each got.

#3 Add coding parameters and advanced coding functions
  zh/K510_Multimedia_Developer_Guides.md
Labels: documentation

#9 Modify the document: ffmpeg supports RTMP streaming
  zh/K510_Multimedia_Developer_Guides.md
Labels: improvement

#11 Correct 720p60 & vga@75fps encoding cmd line
  zh/K510_Multimedia_Developer_Guides.md
Labels: improvement

#13 fix files format and add markdownlint ci
  .github/pull_request_template.md
  .github/workflows/markdown_check.yml
  .markdownlint.json
  README.md
  zh/K510_AI_Application_Guides.md
  zh/K510_CRB_V1.2_Hardware_Guide.md
  zh/K510_Drm_Developer_Guides.md
  zh/K510_ISP_Tuning_Tool_Guides.md
  zh/K510_Linux_Kernel_Driver_Developer_Guides.md
  zh/K510_Mailbox_Developer_Guides.md
  zh/K510_Multimedia_Developer_Guides.md
  zh/K510_SDK_Application_Guides.md
  zh/K510_SDK_Build_and_Burn_Guide.md
  zh/K510_SDK_DSP_CORE_Guide.md
  zh/K510_System_memory_map.md
  zh/K510_U-Boot_Developer_Guides.md
  zh/K510_V4l2_Developer_Guides.md
  zh/K510_V4l2_Sensor_Developer_Guides.md
  zh/K510_nncase_Developer_Guides.md
Labels: improvement

#15 fix docs and add markdownlink check ci
  .github/CONTRIBUTING.md
  .github/config/markdownlink.json
  .github/workflows/markdown_check.yml
  README.md
  zh/K510_CRB_V1.2_Hardware_Guide.md
  zh/K510_Drm_Developer_Guides.md
  zh/K510_Linux_Kernel_Driver_Developer_Guides.md
  zh/K510_U-Boot_Developer_Guides.md
Labels: improvement

#18 Ffmpeg push RTMP video stream command error
  zh/K510_Multimedia_Developer_Guides.md
Labels: errata

#27 Modify document: Add coding function:Deblocking, slice, entropy coding, SEI.Provide detailed description of coding parameters.
  zh/K510_Multimedia_Developer_Guides.md
Labels: improvement
